### ISSUE TITLE
Leverage Node.js embedded ICU

### ISSUE THREAD

**Issue by TimothyGu** [martinheidegger/wcsize#1]
Node.js core has `process.binding('icu').getStringWidth` which leverages the embedded ICU Unicode database for char width calculation (for readline). With careful usage (wrapping everything in a `try {} catch (e) {}` to protect against Node.js internal changes), it should give better performance and be more actively maintained than the fixed Unicode table in this module. See [here](https://github.com/nodejs/node/blob/29353e5a992c1e7f92fafa4d1429e0f8dd494155/src/node_i18n.cc#L748-L855) for the implementation.

**Comment by martinheidegger** [comment]
@TimothyGu `wcsize` was my attempt to have a quick no-dependency implementation to also works  in the browser. Historically I wrote it as part of the implementation for [`wcstring`](https://github.com/martinheidegger/wcstring). `wcstring` again is without native dependencies. And it does cache the results in [`index.js#L1`](https://github.com/martinheidegger/wcstring/blob/master/index.js#L1). Replacing that logic with the `getStringWidth` seems like a good idea. But because of the caching I am not sure how much gain in practice we will get.

**Comment by lydell** [comment]
`process.binding` seems to be deprecated: https://nodejs.org/api/deprecations.html#DEP0111
